// <auto-generated />
namespace DataBaseLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class User_Table_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Table_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202001211158299_User_Table_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
